name: Build packages.json
on: 
  workflow_call:
    secrets:
      token:
        required: false
    inputs:
      owner:
        type: string
        required: false
jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "Triggered from: ${{ github.event.client_payload.repository || github.repository }} by: ${{ github.event.sender.login }}"
      - name: Setup
        run: |
          composer config -g allow-plugins.piotrpress/composer-streams true
          composer global require piotrpress/composer-streams
      - name: Auth
        env:
          token: ${{ secrets.token }}
        if: ${{ env.token }}
        run: |
          composer config -g http-basic.github.com x-oauth-basic ${{ secrets.token }}
      - name: Update
        run: |
          composer stream github://${{ inputs.owner || github.repository_owner }} > packages.json
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: packages.json
          path: packages.json
          overwrite: true